//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ClientView:public drogon::DrTemplate<ClientView>
{
public:
	ClientView(){};
	virtual ~ClientView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
